language: elixir
elixir:
  - "1.9"
addons:
  postgresql: "12"
env:
  - MIX_ENV=test
script:
  - mix test
  - mix coveralls.travis
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json
 
after_success:
  - bash <(curl -s https://codecov.io/bash) -e CODECOV_TOKEN || echo "Codecov did not collect coverage reports"
